[package]
name = "super-docker"
version = "0.1.2"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.30.2"
rusqlite = { version = "0.37.0", features = ["bundled"] }

[[bin]]
name = "super-docker"
path = "src/main.rs"
test = false

# short alias - same app, second binary name
[[bin]]
name = "sd"
path = "src/main.rs"
test = false

[[bench]]
name = "hot_paths"
harness = false
