[package]
name = "super-docker-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
super-docker = { path = ".." }

[[bin]]
name = "json"
path = "fuzz_targets/json.rs"
test = false
doc = false
bench = false

[[bin]]
name = "log_ingest"
path = "fuzz_targets/log_ingest.rs"
test = false
doc = false
bench = false
